name: Build



on: [pull_request, push]



jobs:
build:
runs-on: ubuntu-latest



steps:
    - name: Checkout the code
    uses: actions/checkout@v2

    - name:
        Run a one-line script
    run: 
    ./gradlew build
